//
// Generated file, do not edit! Created by opp_msgc 4.5 from contFrame.msg.
//

#ifndef _QUEUEING_CONTFRAME_M_H_
#define _QUEUEING_CONTFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef QUEUEING_API 
#  if defined(QUEUEING_EXPORT)
#    define QUEUEING_API  OPP_DLLEXPORT
#  elif defined(QUEUEING_IMPORT)
#    define QUEUEING_API  OPP_DLLIMPORT
#  else
#    define QUEUEING_API 
#  endif
#endif


namespace queueing {

/**
 * Class generated from <tt>contFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet ContFrame {
 *     int frameType=0;
 *     string moduleName;
 *     int moduleID;
 *     int moduleType;
 *         
 * }
 * </pre>
 */
class QUEUEING_API ContFrame : public ::cPacket
{
  protected:
    int frameType_var;
    opp_string moduleName_var;
    int moduleID_var;
    int moduleType_var;

  private:
    void copy(const ContFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ContFrame&);

  public:
    ContFrame(const char *name=NULL, int kind=0);
    ContFrame(const ContFrame& other);
    virtual ~ContFrame();
    ContFrame& operator=(const ContFrame& other);
    virtual ContFrame *dup() const {return new ContFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);
    virtual const char * getModuleName() const;
    virtual void setModuleName(const char * moduleName);
    virtual int getModuleID() const;
    virtual void setModuleID(int moduleID);
    virtual int getModuleType() const;
    virtual void setModuleType(int moduleType);
};

inline void doPacking(cCommBuffer *b, ContFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ContFrame& obj) {obj.parsimUnpack(b);}

}; // end namespace queueing

#endif // _QUEUEING_CONTFRAME_M_H_
