//
// Generated file, do not edit! Created by opp_msgc 4.5 from P3DBroadcastParameter.msg.
//

#ifndef _QUEUEING_P3DBROADCASTPARAMETER_M_H_
#define _QUEUEING_P3DBROADCASTPARAMETER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef QUEUEING_API 
#  if defined(QUEUEING_EXPORT)
#    define QUEUEING_API  OPP_DLLEXPORT
#  elif defined(QUEUEING_IMPORT)
#    define QUEUEING_API  OPP_DLLIMPORT
#  else
#    define QUEUEING_API 
#  endif
#endif


namespace queueing {

/**
 * Class generated from <tt>P3DBroadcastParameter.msg</tt> by opp_msgc.
 * <pre>
 * message P3DBroadcastParameter {
 * 	int numberOfTimeslots;
 * 	int numberOfFrames;
 * 	int timeslotSize;
 * 	simtime_t timeslotDuration;
 * 	simtime_t guardTime;
 * }
 * </pre>
 */
class QUEUEING_API P3DBroadcastParameter : public ::cMessage
{
  protected:
    int numberOfTimeslots_var;
    int numberOfFrames_var;
    int timeslotSize_var;
    simtime_t timeslotDuration_var;
    simtime_t guardTime_var;

  private:
    void copy(const P3DBroadcastParameter& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const P3DBroadcastParameter&);

  public:
    P3DBroadcastParameter(const char *name=NULL, int kind=0);
    P3DBroadcastParameter(const P3DBroadcastParameter& other);
    virtual ~P3DBroadcastParameter();
    P3DBroadcastParameter& operator=(const P3DBroadcastParameter& other);
    virtual P3DBroadcastParameter *dup() const {return new P3DBroadcastParameter(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getNumberOfTimeslots() const;
    virtual void setNumberOfTimeslots(int numberOfTimeslots);
    virtual int getNumberOfFrames() const;
    virtual void setNumberOfFrames(int numberOfFrames);
    virtual int getTimeslotSize() const;
    virtual void setTimeslotSize(int timeslotSize);
    virtual simtime_t getTimeslotDuration() const;
    virtual void setTimeslotDuration(simtime_t timeslotDuration);
    virtual simtime_t getGuardTime() const;
    virtual void setGuardTime(simtime_t guardTime);
};

inline void doPacking(cCommBuffer *b, P3DBroadcastParameter& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, P3DBroadcastParameter& obj) {obj.parsimUnpack(b);}

}; // end namespace queueing

#endif // _QUEUEING_P3DBROADCASTPARAMETER_M_H_
